### PR TITLE
Repair UUIDs duplicates (storage 3.1 upgrade)

### LINKED ISSUE #122: previous mail gets sent again when previous mail has same subject as current mail
Repro:

    Player1 sends mail with topicA and textA to Player2
    Player2 sends mail with topicA and textB to Player2

Wrong: Player2 receives topicA and textA in the first mail, and then topicA and textA in the second mail
Expected: Player2 receives topicA and textA in the first mail, and then topicA and textB in the second mail

for my reference 5504

### PR DESCRIPTION
**Pull request by Athozus**
This is a proposal for the most important hotfix of this release. What does it do ?
* It first checks, when giving an UUID, if it is not already used in the database ;
* At the startup, in after migrating in `migrate.lua`, it checks for non-duplicates, and if there are, it gives new ID to all messages that are not the same (`mail.are_message_sames()`). Of course, because it iterates through all messages, after fixing message1, it checks message2, so if there is a message3 also concerned by the duplicate, it is fixed in the message2 loop.

I tested it with 10 000 messages, it runs quite good (no performance loss). If you want to test it, you can use the `/mail_spam` command written in #103.

Of course, performance can still be improved, but that's not really a mess here.

I ping @Bastrabun because he was the first who noticed the issue on Your Land.

Fix #122, #126.

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
did i read this correctly: the "repair" code runs on _every_ startup, right?

and: are you sure this is needed, uuid collisions should be borderline impossible :/

**Comment by S-S-X** [comment]
Could you @Athozus or @Bastrabun reveal what is the issue with current RNG or implementation? And if there's issues with RNG on Your Land could it be that RNG is compromised by one of the mods?

It is true that it is easy to trash math.random, if that's the issue then better solution would be to use Minetest's own RNG API like PcgRandom which you could, if you feel paranoid, initialize with SecureRandom.

File: util/uuid.lua [hunk 1]
```diff
@@ -1,9 +1,49 @@
...
-end
\ No newline at end of file
+    local candidate_uuid
+    repeat
+        candidate_uuid = string.gsub(template, '[xy]',
+            function (c)
+                local v = (c == 'x') and random(0, 0xf) or random(8, 0xb)
+                return string.format('%x', v)
+            end)
+    until not mail.is_uuid_existing(candidate_uuid)
```
Comment (S-S-X) [inline util/uuid.lua:47]: I'd say just calling this even once is unacceptable, checking UUID every time new UUID is generated.

Either fix issues with RNG or use auto increment ID instead.

**Comment by S-S-X** [comment]
> Maybe, it should not be run at every startup, but like when passed into a command ?

If it is to fix duplicates caused by now fixed bug then you could just automatically run it once and then increment database version to v3.1 or v4 depending on which number you like most / if you want to use some versioning scheme that differentiates breaking changes from bug fixes and feature additions.

**Comment by Athozus** [comment]
Applied your suggestions :+1:

**Comment by Athozus** [comment]
`docker-compose` command-not-found in the checks. Without that error, they all have succeed. I don't understand how to fix this.

File: util/uuid.lua [hunk 2]
```diff
@@ -1,9 +1,49 @@
...
+function mail.are_message_sames(a, b)
+	return a.time == b.time
+	   and a.from == b.from
+	   and a.to == b.to
+	   and a.cc == b.cc
+	   and a.bcc == b.bcc
+	   and a.subject == b.subject
+	   and a.body == b.body
+end
+
```
Comment (S-S-X) [inline util/uuid.lua:37]: Pretty sure these belong to migrate.lua, not here. I mean these probably shouldn't be needed or used for anything besides one time repairs and should also be local instead of exposed through global `mail`.

**Comment by S-S-X** [comment]
> `docker-compose` command-not-found in the checks. Without that error, they all have succeed. I don't understand how to fix this.

I guess it is issue with action runner, not mail mod. @BuckarooBanzay might have idea.

File: util/uuid.lua (hunk 2 above)
Comment (S-S-X) [reply util/uuid.lua:37]: `mail.is_uuid_existing(uuid)` should NOT be used in `util/uuid.lua`.
You should NOT have to check newly generated UUID's.

Comment (Athozus) [reply util/uuid.lua:37]: I know that the probability is very very ridiculous, but there is still a chance of two generated UUIDs might be the same. It is just here to avoid it.

Comment (S-S-X) [reply util/uuid.lua:37]: Yeah if either RNG is very bad or if you generate few exabytes of UUID's then you start seeing some percentages you can actually write down readable without scientific notation.

But problem is that if RNG isn't very badly broken it would take hundreds of years non stop generating UUID's and you still don't have any meaningful chance of getting random collision.

If RNG is that badly broken then fix it.

Comment (BuckarooBanzay) [reply util/uuid.lua:37]: > I know that the probability is very very ridiculous, but there is still a chance of two generated UUIDs might be the same. It is just here to avoid it.

As @S-S-X said: this should not happen and you should not have to mitigate against this, the bug (if there even is one) must be elsewhere.

if uuid's really were that bad then every software company in the world would have a major problem, just saying...

**Comment by BuckarooBanzay** [comment]
> docker-compose command-not-found in the checks

had that somewhere else yesterday too, seems like a github issue, just ignore it :)

@Bastrabun could please elaborate on the issue, i'm curious how something like this would happen :thinking:

**Comment by Athozus** [comment]
> > docker-compose command-not-found in the checks
> 
> had that somewhere else yesterday too, seems like a github issue, just ignore it :)

I ran it, it was fixed, thanks !

File: util/uuid.lua (hunk 2 above)
Comment (Athozus) [reply util/uuid.lua]: Done in c052e59

**Comment by Athozus** [comment]
Applied you suggestions in latest commit c052e59. Sounds ready to merge (I requested a review anyway).

So now it focuses only on `migrate.lua`, it no longer checks for a chance over millions (if not billions) of duplicate.

The risk was of 1 over 16<sup>30</sup>.12 = 1,6.10<sup>37</sup>. Minetest servers can be very popular, but :grin:

**Comment by Athozus** [comment]
> @Bastrabun could please elaborate on the uuid/rng-issue, i'm curious how something like this would happen 🤔

Btw, it was not an error from RNG, it was due to the bug fixed in #137, which use the selected message id into `compose.lua`, so for a new message.

File: util/uuid.lua (hunk 2 above)
Comment (S-S-X) [reply util/uuid.lua]: > Hmm okay yes, there was never issue but indeed it's not really good, notably on balance benefit/risk. On « big » servers it can take so much time for still many millions of chance under a potential duplicate.

About balance benefit/risk, there's virtually zero risk. I get that it isn't easy to understand mind bogglingly small chances but really here risk translates to zero.

There's a lot higher risk that complicated implementation causes another bug that makes whole thing useless.

To put numbers another way, you'd assume each UUID weights about 1.5 milligrams (two average snowflakes weight about this much, or ~10 sand grains). You then take all possible UUIDs we can generate and put them together, you'd get object that weights about the same as our sun.

If you take some few trillions of UUIDs from that pile it would be impossible to notice that anyone touched it. In terms of mail database, if you had that many mails it would take some 250 terabytes to one petabyte on your server storage and percentage you used up is about 0.000000000000000000000001505%.

Yeah, I know sun is also mind bogglingly large sorry about that. But anything else would make single unit mind bogglingly small for comparisons. It is pretty much impossible to make up anything that is easy to understand.

I hope I got numbers right and bit more accurate than last time, I believe so.

File: migrate.lua [hunk 3]
```diff
@@ -80,20 +80,114 @@ local function migrate_v2_to_v3()
...
+	return a.time == b.time
+	   and a.from == b.from
+	   and a.to == b.to
+	   and a.cc == b.cc
+	   and a.bcc == b.bcc
+	   and a.subject == b.subject
+	   and a.body == b.body
+end
+
+local function repair_box(playername, box)
```
Comment (S-S-X) [inline migrate.lua:119]:
```suggestion
local function fix_duplicate_uuids(playername, box)
```
Minor but to tell what it actually does, `repair_box` is a bit generic.

File: migrate.lua [hunk 4]
```diff
@@ -80,20 +80,114 @@ local function migrate_v2_to_v3()
...
+-- repair database for uuid doublons
+local function repair_storage()
+	-- iterate through players
+	for _, k in ipairs(mail.storage:get_keys()) do
+		if string.sub(k,1,5) == "mail/" then
+			local p = string.sub(k, 6)
+			repair_box(p, "inbox")
+			repair_box(p, "outbox")
+			repair_box(p, "drafts")
+			repair_box(p, "trash")
```
Comment (S-S-X) [inline migrate.lua:166]: Related to previous, minor naming thing
```suggestion
			fix_duplicate_uuids(p, "inbox")
			fix_duplicate_uuids(p, "outbox")
			fix_duplicate_uuids(p, "drafts")
			fix_duplicate_uuids(p, "trash")
```

File: util/uuid.lua
Comment (S-S-X) [inline util/uuid.lua:1]: Better just remove this file from changeset, there's no real changes.
Revert to master branch version.

**Review by S-S-X — CHANGES_REQUESTED** [review]
Minor suggestions for migrate.lua, don't really care if these get applied or not.

util/uuid.lua however should be just reverted to master branch as it has not been changed other than whitespace.

Drop uuid.lua from changeset and fine for me then.

File: migrate.lua (hunk 4 above)
Comment (Athozus) [reply migrate.lua]: Done :heavy_check_mark:

**Review by S-S-X — APPROVED** [review]
Seems fine, didn't test however.

**Comment by Athozus** [comment]
Note that it is still upgrading to `3.1`, I didn't changed that. It is an important PR so I prefer to remind you, as it was discussed a lot on our servers.
